# Generated by Django 4.2.5 on 2023-09-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_platform', '0002_alter_lessonview_user_alter_product_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
