# Generated by Django 4.2.5 on 2023-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_platform', '0004_remove_lessonview_time_watched_in_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time_watching',
        ),
        migrations.AddField(
            model_name='lessonview',
            name='time_watching',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
