# Generated by Django 4.2.5 on 2023-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_platform', '0005_remove_lesson_time_watching_lessonview_time_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_watched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
