# Generated by Django 4.2.5 on 2023-09-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_platform', '0006_lessonview_last_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='last_watched',
            field=models.DateTimeField(),
        ),
    ]
